fix contact numbering for multiple electrodes
SFB-ELAINE/OSS-DBSv2 pull request #25
Opened 2024-05-31 08:23 UTC by JPPayonk

When using multiple electrodes, the first contact of the second, third, ... electrode was skipped.
This is fixed now by using the electrode index when numbering

2024-06-02 23:17 UTC, j-zimmermann requested changes
This fix does not fix the bug.
The problem in the example you sent me is related to the way that surfaces get added to the model. There are actually three `BrainSurface` contacts because for every electrode a `BrainSurface` seems to be added.

Please check the part where the electrodes and other surfaces get added to the model, the bug is hidden there.

2024-06-03 08:50 UTC, JPPayonk commented
You are right, the real problem was that we added a BrainSurface for each electrode. I have simply removed this step from the loop, so that the BrainSurface is now only used once, regardless of the number of electrodes.

2024-06-03 20:33 UTC, j-zimmermann approved these changes

2024-06-03 20:34 UTC, j-zimmermann commented
That looks good; thanks for fixing it 👍

2024-06-03 20:34 UTC, merged